<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.13</version>
        <relativePath/>
    </parent>

    <groupId>io.github.zzih</groupId>
    <artifactId>arion-dolphin</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <name>Arion Dolphin</name>
    <description>Workflow publishing and scheduling management platform for DolphinScheduler</description>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <modules>
        <module>arion-dolphin-common</module>
        <module>arion-dolphin-domain</module>
        <module>arion-dolphin-dao</module>
        <module>arion-dolphin-service</module>
        <module>arion-dolphin-api</module>
        <module>arion-dolphin-client</module>
    </modules>

    <properties>
        <revision>0.1.0-SNAPSHOT</revision>
        <java.version>21</java.version>
        <lombok.version>1.18.44</lombok.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <arion-dolphin.version>${revision}</arion-dolphin.version>

        <!-- Dependencies -->
        <mybatis-plus.version>3.5.9</mybatis-plus.version>
        <spring-dotenv.version>4.0.0</spring-dotenv.version>
        <dotenv-java.version>3.0.2</dotenv-java.version>
        <auto-service.version>1.1.1</auto-service.version>
        <dolphinscheduler.version>3.4.1</dolphinscheduler.version>
        <springdoc.version>2.8.6</springdoc.version>
        <knife4j.version>4.5.0</knife4j.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- ==================== Internal Modules ==================== -->
            <dependency>
                <groupId>io.github.zzih</groupId>
                <artifactId>arion-dolphin-common</artifactId>
                <version>${arion-dolphin.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zzih</groupId>
                <artifactId>arion-dolphin-domain</artifactId>
                <version>${arion-dolphin.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zzih</groupId>
                <artifactId>arion-dolphin-dao</artifactId>
                <version>${arion-dolphin.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zzih</groupId>
                <artifactId>arion-dolphin-service</artifactId>
                <version>${arion-dolphin.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.zzih</groupId>
                <artifactId>arion-dolphin-client</artifactId>
                <version>${arion-dolphin.version}</version>
            </dependency>

            <!-- ==================== Third Party ==================== -->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>
            <dependency>
                <groupId>me.paulschwarz</groupId>
                <artifactId>spring-dotenv</artifactId>
                <version>${spring-dotenv.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.cdimascio</groupId>
                <artifactId>dotenv-java</artifactId>
                <version>${dotenv-java.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.auto.service</groupId>
                <artifactId>auto-service</artifactId>
                <version>${auto-service.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.auto.service</groupId>
                <artifactId>auto-service-annotations</artifactId>
                <version>${auto-service.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${springdoc.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.xiaoymin</groupId>
                <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
                <version>${knife4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.dolphinscheduler</groupId>
                <artifactId>dolphinscheduler-dao</artifactId>
                <version>${dolphinscheduler.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.apache.dolphinscheduler</groupId>
                        <artifactId>dolphinscheduler-task-api</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.dolphinscheduler</groupId>
                        <artifactId>dolphinscheduler-spi</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.dolphinscheduler</groupId>
                        <artifactId>dolphinscheduler-service-shared</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-jdbc</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.baomidou</groupId>
                        <artifactId>*</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.postgresql</groupId>
                        <artifactId>*</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.h2database</groupId>
                        <artifactId>*</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.curator</groupId>
                        <artifactId>*</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.zookeeper</groupId>
                        <artifactId>*</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>com.google.auto.service</groupId>
                            <artifactId>auto-service</artifactId>
                            <version>${auto-service.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>1.6.0</version>
                <configuration>
                    <updatePomFile>true</updatePomFile>
                    <flattenMode>resolveCiFriendliesOnly</flattenMode>
                </configuration>
                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>2.44.4</version>
                <configuration>
                    <java>
                        <eclipse>
                            <file>${maven.multiModuleProjectDirectory}/style/arion-dolphin-formatter.xml</file>
                        </eclipse>
                        <removeUnusedImports/>
                        <licenseHeader>
                            <file>${maven.multiModuleProjectDirectory}/style/license-header</file>
                        </licenseHeader>
                        <importOrder>
                            <file>${maven.multiModuleProjectDirectory}/style/arion-dolphin.importorder</file>
                        </importOrder>
                    </java>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <phase>validate</phase>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>3.6.0</version>
                <configuration>
                    <configLocation>${maven.multiModuleProjectDirectory}/style/checkstyle.xml</configLocation>
                    <includeTestSourceDirectory>true</includeTestSourceDirectory>
                    <consoleOutput>true</consoleOutput>
                    <failOnViolation>true</failOnViolation>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <phase>validate</phase>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>com.puppycrawl.tools</groupId>
                        <artifactId>checkstyle</artifactId>
                        <version>10.21.4</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
    <distributionManagement>
        <repository>
            <id>zzih-nexus-releases</id>
            <url>https://nexus.zzih.net:81/repository/maven-releases/</url>
        </repository>
        <snapshotRepository>
            <id>zzih-nexus-snapshots</id>
            <url>https://nexus.zzih.net:81/repository/maven-snapshots/</url>
        </snapshotRepository>
    </distributionManagement>
</project>
